#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Fri Oct  3 17:40:58 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade




class Ventana4(wx.Frame):
    def __init__(self, parent, informacion = "", subtotal1= 0, informacion2 = "", subtotal2 = 0):
        # begin wxGlade: Ventana4.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)

        self.SetSize((677, 577))
        self.SetTitle("Ticket-Cineplus")
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(192, 192, 192))

        self.infoTaquilla = informacion
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal1
        self.subtotalDulceria = subtotal2
        self.total = self.subtotalTaquilla+self.subtotalDulceria


        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilllacine.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        lbTicket = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        lbTicket.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        grid_sizer_1.Add(lbTicket, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilllacine.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_2.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY,f"{self.infoTaquilla}")
        lbTaquilla.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY,f"Subtotal: ${self.subtotalTaquilla}")
        self.lbSubtotalTaquilla.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(self.lbSubtotalTaquilla, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        label_5.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(label_5, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY,f"{self.infoDulceria}")
        self.lbDulceria.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(self.lbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY,f"Subtotal: ${self.subtotalDulceria}")
        self.lbSubtotalDulceria.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(self.lbSubtotalDulceria, 0, 0, 0)

        self.lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"TOTAL: $ {self.subtotalTaquilla + self.subtotalDulceria}")
        self.lbTotal.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        sizer_2.Add(self.lbTotal, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        grid_sizer_2.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        self.btnFinalizar.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Century"))
        grid_sizer_2.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
       wx.Exit()
       event.Skip()

    def finalizarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        print("Venta Realizada")
        v2 = Ventana2(self)
        v2.Show()
        self.Hide()
        event.Skip()
        

# end of class Ventana4
class Ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style=wx.DEFAULT_FRAME_STYLE)
        self.SetSize((618, 741))
        self.SetTitle("frame_2")
        print(f"Datos de la ventana 2:\n Informacion: {informacion} \n")
        print(f"subtotal: {subtotal}")
        self.SetBackgroundColour(wx.Colour(192, 192, 192))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        #Variables de instancia
        self.SubtotalDulceria = 0
        self.infoDulceria = ""        
        self.infoTaquilla = informacion
        self.subtotalTaquilla = subtotal

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logodulceria1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        label_1.SetFont(wx.Font(22, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logodulceria1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboB.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_6.Add(self.spComboB, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_6.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        label_2.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_7.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch")
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_7.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco ch")
        label_4.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_7.Add(label_4, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo1.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(bitmap_3, 0, 0, 0)

        grid_sizer_8 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboC.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_8.Add(self.spComboC, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $210")
        label_5.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_9.Add(label_5, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 Palomitas Gd")
        label_6.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_9.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 refrescos md")
        label_7.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_9.Add(label_7, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 nachos y 1 hotdog")
        label_8.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_9.Add(label_8, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(bitmap_4, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_3.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboF.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_11.Add(self.spComboF, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(6, 1, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $320")
        label_9.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_12.Add(label_9, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 Palomitas Extra gd")
        label_10.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_12.Add(label_10, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "4 Refrescos md")
        label_11.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_12.Add(label_11, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 Nachos")
        label_12.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_12.Add(label_12, 0, 0, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 hotdogs")
        label_13.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_12.Add(label_13, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 helado ch")
        label_14.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_12.Add(label_14, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(bitmap_5, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_3.Add((0, 0), 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_25 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_25, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_25.Add(bitmap_6, 0, 0, 0)

        grid_sizer_26 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_25.Add(grid_sizer_26, 1, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_19.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_26.Add(label_19, 0, 0, 0)

        grid_sizer_27 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_26.Add(grid_sizer_27, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasCh.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_27.Add(self.spPalomitasCh, 0, 0, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas $40")
        label_20.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_27.Add(label_20, 0, 0, 0)

        grid_sizer_28 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_26.Add(grid_sizer_28, 1, wx.EXPAND, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasMd.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_28.Add(self.spPalomitasMd, 0, 0, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas $60")
        label_21.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_28.Add(label_21, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_29 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_26.Add(grid_sizer_29, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasG.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_29.Add(self.spPalomitasG, 0, 0, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes $90")
        label_22.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_29.Add(label_22, 0, 0, 0)

        grid_sizer_30 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_30, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logorefresco.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_30.Add(bitmap_7, 0, 0, 0)

        grid_sizer_31 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_30.Add(grid_sizer_31, 1, wx.EXPAND, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_23.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_31.Add(label_23, 0, 0, 0)

        grid_sizer_33 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_31.Add(grid_sizer_33, 1, wx.EXPAND, 0)

        label_24 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamano")
        label_24.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_33.Add(label_24, 0, 0, 0)

        label_25 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_25.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_33.Add(label_25, 0, wx.ALIGN_CENTER, 0)

        label_26 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_26.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_33.Add(label_26, 0, 0, 0)

        grid_sizer_32 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_31.Add(grid_sizer_32, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Chico", "Mediano", "Grande"], style=wx.CB_DROPDOWN)
        self.cmbTamano.SetFont(wx.Font(8, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_32.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Coca", "Sprite", "Fanta"], style=wx.CB_DROPDOWN)
        self.cmbSabor.SetFont(wx.Font(8, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_32.Add(self.cmbSabor, 0, 0, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidad.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_32.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Century"))
        grid_sizer_32.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:")
        label_15.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_10.Add(label_15, 0, 0, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbProductosAgregados.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_10.Add(self.lbProductosAgregados, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_17.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_5.Add(label_17, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        self.lbSubtotal.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_5.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_13.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bodoni MT"))
        grid_sizer_13.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.CalcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.CalcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.CalcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.CalcularPalomitasGd)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.SubtotalDulceria=self.SubtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combo Basico \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def CalcularComboCuates(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spComboC.GetValue())
        subtotalcombo=numero*210
        self.SubtotalDulceria=self.SubtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combo Cuate \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def CalcularComboFamiliar(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spComboF.GetValue())
        subtotalcombo=numero*320
        self.SubtotalDulceria=self.SubtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combo Familiar \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasCh(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*40
        self.SubtotalDulceria=self.SubtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Ch \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def CalcularPalomitasMd(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*60
        self.SubtotalDulceria=self.SubtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Md \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def CalcularPalomitasGd(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*90
        self.SubtotalDulceria=self.SubtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Gd \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarRefresco(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()
        if tamanyo == "Chico":
            subtotalrefresco=numero*25
        elif tamanyo == "Mediano":
            subtotalrefresco=numero*40
        elif tamanyo == "Grande":
             subtotalrefresco=numero*60

        self.SubtotalDulceria=self.SubtotalDulceria+subtotalrefresco
        self.lbSubtotal.SetLabel(f"${self.SubtotalDulceria}")     

        self.infoDulceria=self.infoDulceria + f"{numero} Refresco: {sabor} tamano {tamanyo}\n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def limpiarD(self):   
        #Limpiamos valores de instancia
        self.SubtotalDulceria=0
        self.infoDulceria=""
        #Limpiamos los valores
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("---")
        self.lbSubtotal.SetLabel("$00.00")

    def limpiarDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        
        pregunta = wx.MessageDialog (self,
        f"Confirmacion de Dulceria.\n"
        f"¿Esta seguro que desea adquirir?\n\n{self.infoDulceria}\n" 
        f"Subtotal Dulceria: ${self.SubtotalDulceria}",
        "Dulceria",style=wx.YES_NO | wx.ICON_QUESTION)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #Cerramos el dialogo

        if respuesta == wx.ID_YES:
          v4 = Ventana4(self, informacion=self.infoTaquilla,
                          subtotal1=self.subtotalTaquilla,
                          informacion2=self.infoDulceria,
                          subtotal2=self.SubtotalDulceria)
          v4.Show()               
          self.limpiarD()
          self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD  

# end of class Ventana3

class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((467, 570))
        self.SetTitle("Taquilla - Cineplus")
        self.SetBackgroundColour(wx.Colour(192, 192, 192))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilllacine.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "\"TAQUILLA\"")
        label_1.SetFont(wx.Font(24, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bernard MT Condensed"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER | wx.RIGHT, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilllacine.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT | wx.RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_2.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_2, 0, wx.ALIGN_CENTER | wx.RIGHT, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_3.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_5.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_5, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Coco", "La Monja", "Sherk"], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(self.cmbPelicula, 0, wx.ALIGN_CENTER, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbSala.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(self.lbSala, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_10 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_10.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_10.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_10.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_10.Add((0, 0), 0, 0, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Cartel2.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, wx.ALL | wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        label_6.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos ($80) :")
        label_7.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_7, 0, wx.ALIGN_CENTER, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.tfAdultos.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(self.tfAdultos, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores ($70) :")
        label_8.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_9.Add(label_8, 0, wx.ALIGN_CENTER, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfMenores.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_9.Add(self.tfMenores, 0, wx.ALIGN_CENTER, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        self.lbSubtotal.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_8.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial Narrow"))
        grid_sizer_8.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.Seleccionpelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

        
    def cargar_imagen(self,ruta):
        bitmap = wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def Seleccionpelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""

        print(f"Pelicula seleccionada: {pelicula}")
        
        if pelicula == "Coco":
            imagen="Cartel2.jpg"
            sala="2"
            horario1="14:00"
            horario2="16:00"
            horario3="18:00"

        elif pelicula == "La Monja":
            imagen="Cartel1.jpg"
            sala="3"
            horario1="18:00"
            horario2="20:00"
            horario3="22:00"

        elif pelicula == "Sherk":
            imagen="Cartel3.jpg"
            sala="1"
            horario1="10:00"
            horario2="12:00"
            horario3="19:00"
        print(f"imagen seleccionada: {imagen}")    

        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula:{pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal= subtotal_a
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido", "Error", wx.OK | wx.ICON_ERROR)
            
        event.Skip()

    def limpiarValores_Campos(self):
   
            self.subtotal=0
            self.adultos=0
            self.menores=0
            self.informacion=""
            self.horarioSeleccionado=""

            self.cargar_imagen("logoCine.jpg")
            self.rbHorario1.SetLabel("00:00")
            self.rbHorario2.SetLabel("00:00")
            self.rbHorario3.SetLabel("00:00")
            self.rbHorario1.SetValue(False)
            self.rbHorario2.SetValue(False)
            self.rbHorario3.SetValue(False)
            self.cmbPelicula.SetSelection(wx.NOT_FOUND)
            self.lbSala.SetLabel("---")
            self.tfAdultos.SetValue("0")
            self.tfMenores.SetValue("0")
            self.lbSubtotal.SetLabel("0")


    def limpiarTaquilla(self,event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion} \n Adultos: {self.adultos} \n Menores de 12 anos: {self.menores}"
        self.informacion = f"{self.informacion} \n Subtotal: {self.subtotal}"
        
        pregunta = wx.MessageDialog(
        self,
        f"Confirmacion de Taquilla.\n"
        f"¿Esta seguro que desea adquirir?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO  | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #Cerramos Dialogo

        if respuesta == wx.ID_YES:
            print(f"Venta de Taquilla realizada\n {self.informacion}")
            v3 = Ventana3(self,informacion=self.informacion,subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

# end of class Ventana2
class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((410, 419))
        self.SetTitle("Inicio de sesion - Cineplus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("E:\\CinePlusJatziri3B\\logoCine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(128, 128, 128))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetForegroundColour(wx.Colour(0, 0, 0))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\CinePlusJatziri3B\\logoCine.jpg", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetMinSize((445, 20))
        lbUsuario.SetForegroundColour(wx.Colour(0, 0, 0))
        lbUsuario.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbUsuario, 0, 0, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((500, 20))
        lbClave.SetForegroundColour(wx.Colour(0, 0, 0))
        lbClave.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbClave, 0, 0, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 33))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 33))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        
        nombre = self.tfUsuario.GetValue  ()
        clave = self.tfClave.GetValue ()

        if nombre =="Jatziri" and clave =="123":
            print(f"¡Bienvenida, {nombre}! Acceso autorizado.")
            v2 = Ventana2(self)
            v2.Show()
            self.Hide()

        else:
            print("Acceso denegado. Usuario o clave incorrectos")

        event.Skip()        

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>

      pregunta = wx.MessageDialog(self, "Se cerrara la ventana.\n Esta seguro de que desea salir?","Confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION)

      respuesta = pregunta.ShowModal()
      pregunta.Destroy()

      if respuesta == wx.ID_YES:
         print("Bye!")
         self.Close()


         print("Event handler 'cerrar_programa' not implemented!")
         event.Skip()

# end of class Ventana1

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
